#!/usr/bin/env python3

"""
Build the planning map from a Habitat scene's navmesh, so the map the planner
uses matches exactly where the robot can drive in Habitat.

The floor is the lowest navmesh level (tables, shelves and the roof are
separate levels/islands and are left out). The grid uses the frame the
Habitat bridge publishes in (ros_x = habitat_x, ros_y = habitat_z) and is
centred on the origin, as MapFrameManager expects.

    ros2 run robo_project navmesh_to_map --navmesh src/environment/IMR_lab8.navmesh \\
        --out src/robo_project/config/maps/imr_lab8_floor

writes imr_lab8_floor.npy (1 = free, 0 = blocked), imr_lab8_floor.yaml and a
preview imr_lab8_floor.png. Select it with map.fname in config.yaml.
"""

import argparse
import math
import os
import struct

import cv2
import numpy as np
from matplotlib.path import Path


def read_navmesh_polygons(path):
    """Ground polygons of a Habitat .navmesh (Recast/Detour 'MSET' tile set) as (N, 3) vertex arrays."""
    data = open(path, 'rb').read()
    magic, _version, num_tiles = struct.unpack_from('<iii', data, 0)
    if magic != 0x4D534554:
        raise ValueError(f"{path} is not a Habitat/Detour navmesh (bad magic)")
    polygons = []
    pos = data.find(b'VAND')  # dtMeshHeader magic 'DNAV', little-endian
    for _ in range(num_tiles):
        if pos < 0:
            break
        header = struct.unpack_from('<5iI9i3f3f3ff', data, pos)
        poly_count, vert_count = header[6], header[7]
        p = pos + 100
        verts = np.frombuffer(data, np.float32, vert_count * 3, p).reshape(-1, 3)
        p += vert_count * 12
        for _ in range(poly_count):
            vs = struct.unpack_from('<6H', data, p + 4)
            _flags, vcount, area_and_type = struct.unpack_from('<HBB', data, p + 28)
            if (area_and_type >> 6) == 0:  # ground polygon, not an off-mesh connection
                polygons.append(verts[list(vs[:vcount])].copy())
            p += 32
        pos = data.find(b'VAND', pos + 4)
    return polygons


def floor_polygons(polygons, tolerance=0.3):
    floor_y = min(float(poly[:, 1].mean()) for poly in polygons)
    return [poly for poly in polygons if abs(float(poly[:, 1].mean()) - floor_y) < tolerance], floor_y


def rasterize(polygons, resolution, margin, erode_cells):
    """Grid centred on the origin: cell (r, c) covers x = res*(c - W//2 .. +1), y = -res*(r - H//2 .. +1)."""
    half_x = max(float(np.abs(poly[:, 0]).max()) for poly in polygons) + margin
    half_y = max(float(np.abs(poly[:, 2]).max()) for poly in polygons) + margin
    width = 2 * math.ceil(half_x / resolution) + 1
    height = 2 * math.ceil(half_y / resolution) + 1
    xc = resolution * (np.arange(width) - width // 2 + 0.5)
    yc = -resolution * (np.arange(height) - height // 2 + 0.5)
    xx, yy = np.meshgrid(xc, yc)
    points = np.c_[xx.ravel(), yy.ravel()]
    free = np.zeros(len(points), dtype=bool)
    for poly in polygons:
        free |= Path(poly[:, [0, 2]]).contains_points(points)   # (habitat_x, habitat_z) = (ros_x, ros_y)
    grid = free.reshape(height, width).astype(np.uint8)
    if erode_cells > 0:
        # Extra safety margin on top of the navmesh's own agent radius.
        k = 2 * erode_cells + 1
        grid = cv2.erode(grid, np.ones((k, k), np.uint8))
    return grid


def main():
    parser = argparse.ArgumentParser(description="Build a planning map from a Habitat navmesh.")
    parser.add_argument('--navmesh', required=True, help='Path to the scene .navmesh')
    parser.add_argument('--out', required=True, help='Output path without extension')
    parser.add_argument('--resolution', type=float, default=0.05, help='Meters per cell (match map.desired_meters_per_pixel)')
    parser.add_argument('--margin', type=float, default=0.3, help='Blocked border around the floor (m)')
    parser.add_argument('--erode', type=int, default=1, help='Extra cells of clearance from obstacles')
    args = parser.parse_args()

    polygons = read_navmesh_polygons(os.path.expanduser(args.navmesh))
    floor, floor_y = floor_polygons(polygons)
    grid = rasterize(floor, args.resolution, args.margin, args.erode)
    n_regions = cv2.connectedComponents(grid, connectivity=4)[0] - 1

    out = os.path.expanduser(args.out)
    name = os.path.basename(out)
    np.save(out + '.npy', grid.astype(np.int8))
    cv2.imwrite(out + '.png', grid * 255)
    with open(out + '.yaml', 'w') as f:
        f.write(f"# Generated by navmesh_to_map from {os.path.basename(args.navmesh)} (floor level y={floor_y:.2f} m).\n"
                f"# Frame: ros_x = habitat_x, ros_y = habitat_z, centred on the origin. 1 = free, 0 = blocked.\n"
                f"image: {name}.npy\n"
                f"resolution: {args.resolution}\n"
                f"coordinate_frame: habitat_world\n")
    print(f"Floor at y={floor_y:.2f} m: {len(floor)} of {len(polygons)} navmesh polygons.")
    print(f"Wrote {out}.npy/.yaml/.png: {grid.shape[1]}x{grid.shape[0]} cells @ {args.resolution} m, "
          f"{int(grid.sum())} free, {n_regions} connected region(s).")


if __name__ == '__main__':
    main()
